update on #9 to fit new project design and resolve conflicts
edenfar/BookScrabble pull request #10
Opened 2023-05-29 10:46 UTC by noamsabb

2023-05-30 12:10 UTC, edenfar requested changes

2023-05-30 12:10 UTC, edenfar commented on src/server/java/server/Player.java
>          throw new UnsupportedOperationException();
Implement this (it should send the data about all the players to the player)

2023-05-30 12:10 UTC, edenfar commented on src/server/java/server/Tile.java
> +    public static Tile fromString(String tileString) {
Check if needed, new tiles should not be created

2023-05-30 12:10 UTC, edenfar commented on src/server/java/server/Player.java
> +        sendToPlayer.accept(name);
Add some prefix that will help the receive identify that it is a player name

2023-05-31 10:57 UTC, noamsabb commented on src/client/java/model/Model.java
> +                    byte[] bagBytes = response.getBytes();
not sure it's really necessary

2023-06-02 07:13 UTC, edenfar requested changes

2023-06-02 11:04 UTC, noamsabb commented on src/server/java/server/Player.java
> +        objectOut.writeObject(o);
We use it to write Java objects to an output stream
objectOut.writeObject(o); writes the serialized form of the object o to the objectOut stream, which in turn writes it to the byteOut stream

2023-06-02 12:57 UTC, edenfar approved these changes

2023-06-02 12:57 UTC, merged