Getting close to a functionnal Game
edenfar/BookScrabble pull request #19
Opened 2023-07-13 19:18 UTC by noamsabb

-Added player score on screen
-Change BoarController parameters to work with actual board with tiles and not string -When player end turn the board get updated to all players with the new word on board -Added an option for players to play null turn if they don't have words to play (still ongoing)

2023-07-14 11:57 UTC, edenfar requested changes

2023-07-14 11:57 UTC, edenfar commented on src/server/java/server/PlayerHandler.java
> +        int raw = Integer.parseInt(substrings[1]);
`row`

2023-07-14 11:57 UTC, edenfar commented on src/server/java/server/Player.java
> +        for (Tile tile: this.tiles){
why twice?

2023-07-14 11:57 UTC, edenfar commented on src/server/java/server/PlayerHandler.java
> +            tiles[i] = player.getTile(c);
verify that `player.getTile(c)` is not `null`

2023-07-14 11:57 UTC, edenfar commented on src/server/java/server/Player.java
> +    private int score = 0;
unecesseary, it is initialized in constructor

2023-07-14 11:57 UTC, edenfar commented on src/server/java/server/Dictionary.java
> +        if (doesExist) {
why?

2023-07-14 11:57 UTC, edenfar commented on src/server/java/server/Board.java
> +
why?

2023-07-14 13:11 UTC, noamsabb commented on src/server/java/server/Player.java
> +        for (Tile tile: this.tiles){
We want to send it this way A1B2C3D4E5F6G7:ABCDEFG because in View we will need both strings (with and without numbers) and like that it's easier to split

2023-07-16 08:54 UTC, ShiraSilverman approved these changes

2023-07-16 09:31 UTC, edenfar approved these changes

2023-07-16 10:14 UTC, merged