cresting new http server
edenfar/BookScrabble pull request #25
Opened 2023-07-19 06:58 UTC by boazsilverman

2023-07-19 16:06 UTC, edenfar requested changes

2023-07-19 16:06 UTC, edenfar commented on src/HTTPServer/MyHttpServer.java
> +            outputStream.write(response.getBytes());
return the boolean `result` rather than string

2023-07-19 16:06 UTC, edenfar commented on src/HTTPServer/MyHttpServer.java
> +                    word = param.substring(5); // Extract the value of "word" parameter
```suggestion
                    word = param.split("word=")[1];
```

2023-07-19 16:06 UTC, edenfar commented on src/HTTPServer/MyHttpServer.java
> +        System.out.println("Server is listening on port 8000");
This line is reachable? After this line the program ends

2023-07-19 16:06 UTC, edenfar commented on src/HTTPServer/MyHttpServer.java
All the dictionary files should move to the `HTTPServer` directory.
The hierarchy should look like:
HTTPServer
- java
  - HTTPServer
    - MyHttpServer
- resources
  - put the files here

2023-07-19 16:06 UTC, edenfar commented on src/server/java/server/Board.java
>      public boolean dictionaryLegal(Word w) {
You should send to the server the file names as well

2023-07-20 20:32 UTC, boazsilverman commented on src/HTTPServer/MyHttpServer.java
> +        System.out.println("Server is listening on port 8000");
<img width="674" alt="image" src="https://github.com/edenfar/BookScrabble/assets/72120141/5bf37e14-c44c-4763-be04-34e8d9883c64">

2023-07-20 21:12 UTC, edenfar requested changes

2023-07-20 21:12 UTC, edenfar commented on src/HTTPServer/java/MyHttpServer.java
> +            String response = result ? "Word found in dictionary" : "Word not found in dictionary";
Return the boolean value and not string

2023-07-20 21:12 UTC, edenfar commented on src/HTTPServer/java/MyHttpServer.java
> +                    word = param.substring(5); // Extract the value of "word" parameter
The comment from the `QueryHandler` is relevant also here

2023-07-20 21:12 UTC, edenfar commented on src/server/java/server/Board.java
> +            String requestUrl = "http://localhost:8000/query?word=" + URLEncoder.encode(wordAsString, StandardCharsets.UTF_8)
Are you sure it works?

2023-07-20 21:12 UTC, edenfar commented on src/server/java/server/Board.java
> +                if (dictionaryLegal(nw,this.fileNames))
You should not pass `this.fileNames`, `dictionaryLegal` knows to access it

2023-07-20 21:12 UTC, edenfar commented on test/java/server/BoardTest.java
> +        Assertions.assertTrue(board.dictionaryLegal(word,board.getFileNames()));
How the server accesses `DICTIONARY_1`?

2023-07-20 21:12 UTC, edenfar commented on src/HTTPServer/java/MyHttpServer.java
> +import server.DictionaryManager;
Move it to the `HTTPServer/java`directory

2023-07-21 04:28 UTC, boazsilverman commented on src/server/java/server/Board.java
> +            String requestUrl = "http://localhost:8000/query?word=" + URLEncoder.encode(wordAsString, StandardCharsets.UTF_8)
yes

2023-07-21 04:28 UTC, boazsilverman commented on src/server/java/server/Board.java
> +                if (dictionaryLegal(nw,this.fileNames))
but there is a constructor without filemname
so they could not be there
also i wanted to keep it global

2023-07-23 22:37 UTC, edenfar approved these changes

2023-07-23 22:37 UTC, merged