Noam merge
edenfar/BookScrabble pull request #26
Opened 2023-07-20 14:14 UTC by noamsabb

-Game fully functionnal (few minor bugs left to fix)
-Re-Design all fxml file to re-design each window
-Added BoardScore and End-Game windows
-Added checkword func that will get us the actual word played and not only the tiles, taking care to add to the word the tile that was already on the screen
-Words can now be set on board in any order player want
-Errors handeling, pop-up window open to player in case an error happen letting him know and then letting him fix it

2023-07-20 21:04 UTC, edenfar requested changes

2023-07-20 21:04 UTC, edenfar commented on src/server/java/server/Game.java
> +    public void playTurn(Player player, Word word, Word wordToReplaceW) {
You only need `Tiles[] tilesToReplace`

2023-07-20 21:04 UTC, edenfar commented on src/server/java/server/PlayerHandler.java
> +    public static String[] extractSubstrings(String input) {
redundant function

2023-07-21 10:31 UTC, noamsabb commented on src/client/java/org/bookscrabble/BoardController.java
> +    public BoardController() {
We need a no arg controller use it in scoreBoard function line 393

2023-07-21 10:46 UTC, noamsabb commented on src/server/java/server/PlayerHandler.java
> +            String move = in.nextLine();
at this point its necessarily move, and we already have a request variable

2023-07-21 12:58 UTC, edenfar requested changes

2023-07-21 12:58 UTC, edenfar commented on src/client/java/viewmodel/ViewModel.java
> +        if (gamesManager.getGame(gameName.getValue()) != null) {
This check should happen in the server

2023-07-21 12:58 UTC, edenfar commented on src/client/java/viewmodel/ViewModel.java
> +    public void playTurn(String word, int r, int c, boolean vertical, String wordToReplace) {
`tilesToReplace`

2023-07-21 12:58 UTC, edenfar commented on src/server/java/server/Board.java
?

2023-07-21 12:58 UTC, edenfar commented on src/server/java/server/PlayerHandler.java
> +    Board board = new Board();
You have the board of the game

2023-07-23 21:34 UTC, edenfar commented on src/server/java/server/Board.java
> -    public void print() {
why?

2023-07-23 21:34 UTC, edenfar commented on src/server/java/server/Game.java
> +    public Board getGameBoard() {
`getBoard`

2023-07-23 21:34 UTC, edenfar commented on src/server/java/server/PlayerHandler.java
> +            for (Tile t : p.getTiles()) {
Use the function you wrote

2023-07-23 21:34 UTC, edenfar commented on src/server/java/server/PlayerHandler.java
> +        Word word = new Word(tiles, row, col, vertical);
just return it

2023-07-23 21:58 UTC, edenfar approved these changes

2023-07-23 21:58 UTC, merged