Server update
edenfar/BookScrabble pull request #4
Opened 2023-05-19 15:19 UTC by noamsabb

close #2; Server update, few functions for testing it are in comments, now working with thread  each client can connect in parallel
Still need to fully adapt the server to the project clients/players connections

2023-05-19 15:25 UTC, edenfar commented on test/java/server/BoardTest.java
> +import org.graalvm.compiler.graph.Node;
redundant

2023-05-19 15:56 UTC, edenfar requested changes

2023-05-19 15:56 UTC, edenfar commented on src/server/PlayerHandler.java
> +    //Test of the server
The test should be in the `test` directory

2023-05-19 15:56 UTC, edenfar commented on src/server/PlayerHandler.java
> +                Socket server=new Socket("localhost", port);
format code

2023-05-19 15:56 UTC, edenfar commented on src/server/MyServer.java
> +                    // Maximum thread count reached, send "Can't connect" message to the client
redudant comment

2023-05-19 15:56 UTC, edenfar commented on src/server/MyServer.java
> +        threadPool.execute(this::startServer);
the server should not run in the thread pool where the clients are handled

2023-05-19 15:56 UTC, edenfar commented on src/server/MyServer.java
> +                if (activeThreads.get() >= maxThreadCount) {
Doesn't the thread pool handles for free the limit of the connected clients?

2023-05-19 15:56 UTC, edenfar commented on src/server/MyServer.java
> +        } catch (IOException | InterruptedException e) {
The `InterruptedException` of the test `handleClient` should be catched within the `handleClient` method, not here

2023-05-19 15:56 UTC, edenfar commented on src/server/ClientHandler.java
> +    void handleClient(InputStream inFromClient, OutputStream outToClient) throws InterruptedException;
`handleClient` should not throw `InterruptedException`, it should catch it

2023-05-20 22:57 UTC, noamsabb commented on src/server/PlayerHandler.java
> +                Socket server=new Socket("localhost", port);
Don't understand the review here

2023-05-21 05:32 UTC, edenfar commented on src/server/PlayerHandler.java
> +                Socket server=new Socket("localhost", port);
Make the code more readable using `Ctrl+Alt+L` on IntelliJ (e.g., it makes `a=b` into `a = b`)

2023-05-24 15:22 UTC, edenfar requested changes

2023-05-24 15:22 UTC, edenfar commented on src/server/Main.java
> +        // Wait for some time to allow server to finish
Is it needed anymore?

2023-05-24 15:22 UTC, edenfar commented on src/server/PlayerHandler.java
> +
Why?

2023-05-24 15:22 UTC, edenfar commented on src/server/PlayerHandler.java
> +    //Test of the server
Not resolved

2023-05-24 15:22 UTC, edenfar commented on src/server/MyServer.java
> +                        System.out.println("Max thread count reached. Cannot accept more clients at the moment.\n");
Send a notification to the client (if it does not get exception), he should know that he cannot connect

2023-05-24 15:22 UTC, edenfar commented on test/java/server/BoardTest.java
> +        MyServer server = new MyServer(PORT, new PlayerHandler(), 3);
Use a simpler handler, like the one you commented out in PlayerHandler

2023-05-24 15:22 UTC, edenfar commented on test/java/server/BoardTest.java
> +        while (true) {
The server in the tests should stop when it handles all clients (and not wait for input)

2023-05-24 17:10 UTC, noamsabb commented on src/server/PlayerHandler.java
> +    //Test of the server
Can't move this to test directory, it's the handleClient that work with the test for now because the actual one isn't done
When it will be i'll make the test work on it 
For now it's have to stay there in comments

2023-05-28 16:03 UTC, edenfar approved these changes

2023-05-28 16:21 UTC, merged